import { getServerSession } from "next-auth"
import { and, asc, eq, isNull } from "drizzle-orm"
import { NextRequest, NextResponse } from "next/server"
import { authOptions } from "@/lib/auth"
import { db } from "@/lib/db"
import { posItems } from "@/lib/db/schema"
import { assertPosPermission } from "@/lib/pos/server"
export const runtime = "nodejs"
export async function GET(_: NextRequest, { params }: { params: Promise<{ storeId: string }> }) { const s = await getServerSession(authOptions); if (!s?.user.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { storeId } = await params; try { await assertPosPermission(s.user.id, storeId, "catalog:read") } catch { return NextResponse.json({ error: "Forbidden" }, { status: 403 }) }; return NextResponse.json(await db.select().from(posItems).where(and(eq(posItems.storeId, storeId), isNull(posItems.deletedAt))).orderBy(asc(posItems.name))) }
export async function POST(req: NextRequest, { params }: { params: Promise<{ storeId: string }> }) { const s = await getServerSession(authOptions); if (!s?.user.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { storeId } = await params; try { await assertPosPermission(s.user.id, storeId, "catalog:write") } catch { return NextResponse.json({ error: "Forbidden" }, { status: 403 }) }; const body = await req.json().catch(() => null) as Record<string, unknown> | null; if (!body || typeof body.name !== "string" || !body.name.trim() || body.name.trim().length > 80 || !Number.isFinite(Number(body.price)) || Number(body.price) < 0 || !Number.isInteger(Number(body.stockOnHand ?? 0)) || Number(body.stockOnHand ?? 0) < 0) return NextResponse.json({ error: "Invalid item" }, { status: 400 }); const imageUrl = typeof body.imageUrl === "string" && body.imageUrl.trim() ? body.imageUrl.trim().slice(0, 500) : null; const [item] = await db.insert(posItems).values({ storeId, name: body.name.trim(), description: typeof body.description === "string" ? body.description.slice(0, 500) : null, imageUrl, price: String(body.price), stockOnHand: Number(body.stockOnHand ?? 0), lowStockAt: Number.isInteger(Number(body.lowStockAt ?? 0)) ? Number(body.lowStockAt ?? 0) : 0, trackStock: body.trackStock !== false, available: body.available !== false, sku: typeof body.sku === "string" && body.sku.trim() ? body.sku.trim().slice(0, 64) : null, categoryId: typeof body.categoryId === "string" && body.categoryId ? body.categoryId : null, prepStation: typeof body.prepStation === "string" && body.prepStation.trim() ? body.prepStation.trim().slice(0, 48) : null }).returning(); return NextResponse.json(item, { status: 201 }) }
