"use client"

import { motion } from "framer-motion"
import { CheckCircle2, Minus, Plus, QrCode } from "lucide-react"
import { useEffect, useMemo, useState } from "react"
import QRCode from "qrcode"
import { toast } from "sonner"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { useLanguage } from "@/lib/i18n"

type MenuItem = { id: string; name: string; description: string | null; imageUrl: string | null; price: string; stock: number; trackStock: boolean }

export function CustomerOrder({ storeSlug }: { storeSlug: string }) {
  const lang = useLanguage(); const id = lang === "ID"; const [name, setName] = useState(""); const [cart, setCart] = useState<Record<string, number>>({}); const [submitted, setSubmitted] = useState(false); const [menu, setMenu] = useState<MenuItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [accessCode, setAccessCode] = useState(""); const [qr, setQr] = useState("")
  useEffect(() => { let active = true; fetch(`/api/pos/public/${encodeURIComponent(storeSlug)}`).then(async (res) => { if (!res.ok) throw new Error("STORE_NOT_FOUND"); return res.json() }).then((data) => { if (active) setMenu(data.items) }).catch(() => { if (active) setError(id ? "Toko tidak ditemukan atau sedang tutup." : "Store was not found or is closed.") }).finally(() => active && setLoading(false)); return () => { active = false } }, [storeSlug, id])
  useEffect(() => { if (!accessCode) return; let active = true; void QRCode.toDataURL(`CCPOS:${storeSlug}:${accessCode}`, { width: 256, margin: 1, errorCorrectionLevel: "M" }).then((url) => { if (active) setQr(url) }); return () => { active = false } }, [storeSlug, accessCode])
  const adjust = (key: string, amount: number) => setCart((now) => ({ ...now, [key]: Math.max(0, (now[key] ?? 0) + amount) }))
  const count = Object.values(cart).reduce((a, b) => a + b, 0)
  const orderLines = useMemo(() => menu.filter((item) => cart[item.id]).map((item) => ({ itemId: item.id, quantity: cart[item.id] })), [menu, cart])
  const submit = async () => { try { const res = await fetch(`/api/pos/public/${encodeURIComponent(storeSlug)}/orders`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ customerName: name, lines: orderLines }) }); const result = await res.json(); if (!res.ok) throw new Error(result.error); setAccessCode(result.accessCode); setSubmitted(true); toast.success(id ? "Kode pesanan dibuat" : "Order code created") } catch (reason) { toast.error(id ? "Pesanan gagal dibuat." : "Could not create order."); setError(reason instanceof Error ? reason.message : "ORDER_FAILED") } }
  if (submitted) return <main className="mx-auto grid min-h-screen max-w-md place-items-center p-4"><motion.section initial={{ opacity: 0, scale: .97 }} animate={{ opacity: 1, scale: 1 }} className="w-full rounded-xl border bg-card p-6 text-center"><CheckCircle2 className="mx-auto size-10 text-emerald-500"/><h1 className="mt-3 text-lg font-semibold">{id ? "Pesanan terkirim" : "Order sent"}</h1><p className="mt-2 text-sm text-muted-foreground">{id ? "Tunjukkan kode atau QR ini kepada kasir." : "Show this code or QR to your cashier."}</p><div className="mx-auto mt-5 grid size-40 place-items-center rounded-lg bg-white p-2">{qr ? <img src={qr} alt={id ? "Kode QR pesanan" : "Order QR code"} className="size-full"/> : <QrCode className="size-20 text-foreground"/>}</div><p className="mt-3 font-mono text-xl font-bold">{accessCode}</p><p className="mt-2 text-xs text-muted-foreground">{id ? "Kode/QR ini hanya berlaku sekali dan hangus setelah kasir mengonfirmasi pembayaran." : "This code/QR works only once — it becomes invalid after the cashier confirms payment."}</p></motion.section></main>
  return <main className="mx-auto min-h-screen max-w-lg bg-background p-4 sm:p-6"><header className="mb-5"><p className="text-xs font-medium text-primary">CROSSCART · {storeSlug}</p><h1 className="mt-1 text-xl font-semibold">{id ? "Pesan dari meja" : "Order from your table"}</h1><p className="mt-1 text-sm text-muted-foreground">{id ? "Tidak perlu akun — masukkan nama untuk pesanan." : "No account needed — add a name for your order."}</p></header><label className="mb-5 block text-sm font-medium">{id ? "Nama Anda" : "Your name"}<Input className="mt-1.5" value={name} onChange={(e) => setName(e.target.value)} maxLength={80} placeholder={id ? "Contoh: Rani" : "e.g. Rani"}/></label>{error && <p className="mb-3 text-sm text-destructive">{error}</p>}<section className="space-y-2">{loading ? <p className="py-10 text-center text-sm text-muted-foreground">Loading menu…</p> : menu.map((item) => <article key={item.id} className="flex items-center gap-3 rounded-xl border p-3">{item.imageUrl ? <img src={item.imageUrl} alt={item.name} className="size-12 shrink-0 rounded-lg border object-cover"/> : <div className="grid size-12 shrink-0 place-items-center rounded-lg bg-primary/10 text-xs font-bold text-primary">CC</div>}<div className="min-w-0 flex-1"><p className="text-sm font-medium">{item.name}</p><p className="text-xs text-muted-foreground">Rp{Number(item.price).toLocaleString("id-ID")}</p></div><Button size="icon-xs" variant="outline" aria-label="Remove item" onClick={() => adjust(item.id, -1)}><Minus/></Button><span className="w-4 text-center text-sm">{cart[item.id] ?? 0}</span><Button size="icon-xs" aria-label="Add item" disabled={item.trackStock && (cart[item.id] ?? 0) >= item.stock} onClick={() => adjust(item.id, 1)}><Plus/></Button></article>)}</section><Button className="mt-5 w-full" disabled={loading || !name.trim() || !count} onClick={submit}>{id ? "Buat kode pesanan" : "Create order code"}</Button></main>
}
