"use client"

import { AnimatePresence, motion } from "framer-motion"
import { ChefHat, Loader2, RefreshCw } from "lucide-react"
import { useCallback, useEffect, useState } from "react"
import { toast } from "sonner"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { useLanguage } from "@/lib/i18n"

type Store = { id: string; name: string }
type Line = { id: string; nameSnapshot: string; quantity: number; note: string | null }
type Order = { id: string; orderNumber: string; customerName: string; status: "submitted" | "accepted" | "preparing" | "ready"; createdAt: string; lines: Line[] }
const nextStatus: Record<Order["status"], Order["status"]> = { submitted: "accepted", accepted: "preparing", preparing: "ready", ready: "ready" }

export function KitchenBoard() {
  const lang = useLanguage(); const id = lang === "ID"; const [stores, setStores] = useState<Store[]>([]); const [storeId, setStoreId] = useState(""); const [orders, setOrders] = useState<Order[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState<string | null>(null)
  const load = useCallback(async () => { try { if (!storeId) { const found = await fetch("/api/pos/stores", { cache: "no-store" }).then((res) => res.ok ? res.json() : Promise.reject()); setStores(found); setStoreId(found[0]?.id ?? ""); return } const data = await fetch(`/api/pos/stores/${storeId}/kitchen`, { cache: "no-store" }).then((res) => res.ok ? res.json() : Promise.reject()); setOrders(data) } catch { toast.error(id ? "Antrean dapur gagal dimuat." : "Could not load kitchen queue.") } finally { setLoading(false) } }, [storeId, id])
  useEffect(() => { const initial = window.setTimeout(() => void load(), 0); const interval = window.setInterval(() => void load(), 5000); return () => { window.clearTimeout(initial); window.clearInterval(interval) } }, [load])
  const advance = async (order: Order) => { const status = nextStatus[order.status]; if (status === order.status) return; setSaving(order.id); try { const response = await fetch(`/api/pos/stores/${storeId}/kitchen`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ orderId: order.id, status }) }); if (!response.ok) throw new Error(); setOrders((current) => current.map((entry) => entry.id === order.id ? { ...entry, status } : entry)); toast.success(id ? "Status pesanan diperbarui." : "Order status updated.") } catch { toast.error(id ? "Status tidak dapat diubah." : "Could not update status.") } finally { setSaving(null) } }
  const label = (status: Order["status"]) => ({ submitted: id ? "Baru" : "New", accepted: id ? "Diterima" : "Accepted", preparing: id ? "Disiapkan" : "Preparing", ready: id ? "Siap" : "Ready" })[status]
  const action = (status: Order["status"]) => ({ submitted: id ? "Terima" : "Accept", accepted: id ? "Mulai" : "Start", preparing: id ? "Tandai siap" : "Mark ready", ready: id ? "Siap diambil" : "Ready for pickup" })[status]
  return <div className="space-y-4"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="flex items-center gap-2 text-xl font-semibold"><ChefHat className="size-5"/>{id ? "Layar dapur" : "Kitchen board"}</h1><p className="mt-1 text-xs text-muted-foreground">{id ? "Memperbarui otomatis setiap 5 detik." : "Refreshes automatically every 5 seconds."}</p></div><Button variant="outline" size="sm" disabled={loading} onClick={() => void load()}><RefreshCw className={loading ? "animate-spin" : ""}/>{id ? "Muat ulang" : "Refresh"}</Button></header>{stores.length > 1 && <select aria-label="Store" value={storeId} onChange={(event) => setStoreId(event.target.value)} className="h-8 rounded-lg border bg-background px-2 text-sm">{stores.map((store) => <option key={store.id} value={store.id}>{store.name}</option>)}</select>}<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3"><AnimatePresence>{orders.map((order) => <motion.article layout initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, scale: .98 }} key={order.id} className="rounded-xl border bg-card p-4"><div className="flex items-start justify-between gap-2"><div><p className="font-mono text-xs text-muted-foreground">{order.orderNumber}</p><h2 className="mt-1 text-sm font-semibold">{order.customerName}</h2></div><Badge variant="outline">{label(order.status)}</Badge></div><ul className="my-4 space-y-2 border-y py-3">{order.lines.map((line) => <li key={line.id} className="text-sm"><span className="font-semibold">{line.quantity}×</span> {line.nameSnapshot}{line.note && <p className="ml-5 text-xs text-muted-foreground">{line.note}</p>}</li>)}</ul><Button className="w-full" disabled={saving === order.id || order.status === "ready"} onClick={() => void advance(order)}>{saving === order.id && <Loader2 className="animate-spin"/>}{action(order.status)}</Button></motion.article>)}</AnimatePresence>{!loading && !orders.length && <p className="col-span-full rounded-xl border border-dashed py-16 text-center text-sm text-muted-foreground">{id ? "Tidak ada pesanan aktif." : "No active orders."}</p>}</div></div>
}
