"use client"

import { AnimatePresence, motion } from "framer-motion"
import { Check, Clock3, Minus, Plus, QrCode, Search, ShoppingBag, UtensilsCrossed } from "lucide-react"
import { useEffect, useMemo, useState } from "react"
import { toast } from "sonner"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { useLanguage } from "@/lib/i18n"

type Item = { id: string; name: string; category: "Coffee" | "Meals" | "Snacks"; price: number; stock: number }
const copy = {
  EN: { title: "Point of sale", live: "Live service", search: "Search menu…", all: "All", cart: "Current order", empty: "Choose an item to begin", total: "Total", confirm: "Confirm", confirmIn: "Confirm in", paid: "Customer paid?", yes: "Yes, complete", no: "No", ready: "Ready", preparing: "Preparing", stock: "left", demo: "Demo workspace · connect a POS store to serve live data" },
  ID: { title: "Titik penjualan", live: "Layanan aktif", search: "Cari menu…", all: "Semua", cart: "Pesanan saat ini", empty: "Pilih item untuk memulai", total: "Total", confirm: "Konfirmasi", confirmIn: "Konfirmasi dalam", paid: "Pelanggan sudah bayar?", yes: "Ya, selesai", no: "Belum", ready: "Siap", preparing: "Disiapkan", stock: "tersisa", demo: "Ruang demo · hubungkan toko POS untuk data langsung" },
} as const

const money = (value: number, lang: "EN" | "ID") => new Intl.NumberFormat(lang === "ID" ? "id-ID" : "en-US", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(value)

export function PosWorkspace() {
  const lang = useLanguage(); const t = copy[lang]
  const [items, setItems] = useState<Item[]>([]); const [store, setStore] = useState<{ id: string; slug: string; name: string } | null>(null); const [loadingCatalog, setLoadingCatalog] = useState(true); const [storeName, setStoreName] = useState(""); const [creatingStore, setCreatingStore] = useState(false); const [itemName, setItemName] = useState(""); const [itemPrice, setItemPrice] = useState(""); const [itemStock, setItemStock] = useState("0"); const [creatingItem, setCreatingItem] = useState(false)
  const [query, setQuery] = useState(""); const [category, setCategory] = useState("All")
  const [cart, setCart] = useState<Record<string, number>>({}); const [phase, setPhase] = useState<"idle" | "countdown" | "paid" | "done">("idle"); const [seconds, setSeconds] = useState(3)
  useEffect(() => { let active = true; void (async () => { try { const stores = await fetch("/api/pos/stores", { cache: "no-store" }).then(async (res) => { if (!res.ok) throw new Error("STORE_FETCH_FAILED"); return res.json() }); const first = stores[0]; if (!first) return; const catalog = await fetch(`/api/pos/public/${encodeURIComponent(first.slug)}`, { cache: "no-store" }).then(async (res) => { if (!res.ok) throw new Error("CATALOG_FETCH_FAILED"); return res.json() }); if (active) { setStore(first); setItems(catalog.items.map((item: { id: string; name: string; category: string | null; price: string; stock: number }) => ({ id: item.id, name: item.name, category: (["Coffee", "Meals", "Snacks"].includes(item.category ?? "") ? item.category : "Meals") as Item["category"], price: Number(item.price), stock: item.stock }))) } } catch { toast.error(lang === "ID" ? "Gagal memuat data POS." : "Could not load POS data.") } finally { if (active) setLoadingCatalog(false) } })(); return () => { active = false } }, [lang])
  const visible = useMemo(() => items.filter((item) => (category === "All" || item.category === category) && item.name.toLowerCase().includes(query.toLowerCase())), [items, category, query])
  const lines = items.filter((item) => cart[item.id]).map((item) => ({ ...item, qty: cart[item.id] }))
  const total = lines.reduce((sum, line) => sum + line.price * line.qty, 0)
  const adjust = (item: Item, delta: number) => setCart((current) => { const next = Math.max(0, Math.min(item.stock, (current[item.id] ?? 0) + delta)); const result = { ...current }; if (next) result[item.id] = next; else delete result[item.id]; return result })
  const start = () => { setPhase("countdown"); setSeconds(3); let remaining = 3; const timer = window.setInterval(() => { remaining -= 1; setSeconds(remaining); if (remaining === 0) { window.clearInterval(timer); setPhase("paid") } }, 1000) }
  const complete = async () => { if (!store) return; try { const draft = await fetch(`/api/pos/public/${encodeURIComponent(store.slug)}/orders`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ customerName: lang === "ID" ? "Pelanggan langsung" : "Walk-in customer", lines: lines.map((line) => ({ itemId: line.id, quantity: line.qty })) }) }).then(async (res) => { const body = await res.json(); if (!res.ok) throw new Error(body.error); return body }); const paid = await fetch(`/api/pos/stores/${store.id}/orders/${draft.id}/complete`, { method: "POST" }); if (!paid.ok) { const body = await paid.json(); throw new Error(body.error) } setPhase("done"); toast.success(lang === "ID" ? "Pesanan selesai dan stok diperbarui." : "Order completed and stock updated.") } catch { toast.error(lang === "ID" ? "Pesanan tidak dapat diselesaikan." : "Could not complete order."); setPhase("idle") } }
  const createStore = async () => { if (!storeName.trim()) return; setCreatingStore(true); try { const res = await fetch("/api/pos/stores", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: storeName.trim() }) }); const created = await res.json(); if (!res.ok) throw new Error(created.error); setStore(created); setStoreName(""); toast.success(lang === "ID" ? "Toko POS dibuat." : "POS store created.") } catch { toast.error(lang === "ID" ? "Gagal membuat toko." : "Could not create store.") } finally { setCreatingStore(false) } }
  const createItem = async () => { if (!store || !itemName.trim() || !itemPrice) return; setCreatingItem(true); try { const res = await fetch(`/api/pos/stores/${store.id}/items`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: itemName.trim(), price: Number(itemPrice), stockOnHand: Number(itemStock), available: true }) }); const created = await res.json(); if (!res.ok) throw new Error(created.error); setItems((current) => [...current, { id: created.id, name: created.name, category: "Meals", price: Number(created.price), stock: created.stockOnHand }]); setItemName(""); setItemPrice(""); setItemStock("0"); toast.success(lang === "ID" ? "Item ditambahkan." : "Item added.") } catch { toast.error(lang === "ID" ? "Item gagal ditambahkan." : "Could not add item.") } finally { setCreatingItem(false) } }
  return <div className="space-y-4 pb-5">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2"><h1 className="text-xl font-semibold tracking-tight">{t.title}</h1><Badge className="bg-emerald-500/10 text-emerald-700 hover:bg-emerald-500/10 dark:text-emerald-400">{t.live}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{store ? store.name : (lang === "ID" ? "Belum ada toko POS. Buat toko melalui API POS terlebih dahulu." : "No POS store yet. Create one through the POS API first.")}</p></div><Button variant="outline" size="sm" disabled={!store} onClick={() => toast.info(lang === "ID" ? "Pemindaian QR tersedia saat toko terhubung." : "QR scan is ready for this store.")}><QrCode /> Scan code</Button></header>
    {!store && !loadingCatalog && <section className="flex flex-wrap items-end gap-2 rounded-xl border bg-card p-3"><label className="min-w-52 flex-1 text-xs font-medium">{lang === "ID" ? "Nama toko POS" : "POS store name"}<Input className="mt-1" maxLength={20} value={storeName} onChange={(event) => setStoreName(event.target.value)} /></label><Button disabled={!storeName.trim() || creatingStore} onClick={createStore}>{creatingStore ? "…" : (lang === "ID" ? "Buat toko" : "Create store")}</Button></section>}
    {store && <section className="flex flex-wrap items-end gap-2 rounded-xl border bg-card p-3"><label className="min-w-40 flex-1 text-xs font-medium">{lang === "ID" ? "Nama item" : "Item name"}<Input className="mt-1" maxLength={80} value={itemName} onChange={(event) => setItemName(event.target.value)} /></label><label className="w-28 text-xs font-medium">{lang === "ID" ? "Harga" : "Price"}<Input className="mt-1" inputMode="decimal" value={itemPrice} onChange={(event) => setItemPrice(event.target.value)} /></label><label className="w-24 text-xs font-medium">{lang === "ID" ? "Stok" : "Stock"}<Input className="mt-1" inputMode="numeric" value={itemStock} onChange={(event) => setItemStock(event.target.value)} /></label><Button disabled={!itemName.trim() || !itemPrice || creatingItem} onClick={createItem}>{creatingItem ? "…" : (lang === "ID" ? "Tambah item" : "Add item")}</Button></section>}
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_330px]">
      <section className="rounded-xl border bg-card p-3 sm:p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><div className="relative flex-1"><Search className="pointer-events-none absolute left-2.5 top-2 size-4 text-muted-foreground"/><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t.search} className="pl-8"/></div><div className="flex gap-1 overflow-x-auto pb-0.5">{["All", "Coffee", "Meals", "Snacks"].map((name) => <Button key={name} size="sm" variant={category === name ? "secondary" : "ghost"} onClick={() => setCategory(name)}>{name === "All" ? t.all : name}</Button>)}</div></div>
        <div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-4">{loadingCatalog ? <p className="col-span-full py-12 text-center text-sm text-muted-foreground">Loading catalog…</p> : visible.length ? visible.map((item) => <motion.button layout key={item.id} onClick={() => adjust(item, 1)} disabled={item.stock === 0} className="cursor-pointer rounded-lg border bg-background p-3 text-left transition-colors hover:bg-muted disabled:cursor-not-allowed disabled:opacity-50"><div className="grid size-8 place-items-center rounded-md bg-primary/10 text-primary"><UtensilsCrossed className="size-4"/></div><p className="mt-5 truncate text-sm font-medium">{item.name}</p><p className="mt-1 text-xs font-semibold tabular-nums">{money(item.price, lang)}</p><p className="mt-1 text-[11px] text-muted-foreground">{item.stock} {t.stock}</p></motion.button>) : <p className="col-span-full py-12 text-center text-sm text-muted-foreground">{lang === "ID" ? "Belum ada item tersedia." : "No available items."}</p>}</div>
      </section>
      <aside className="h-fit rounded-xl border bg-card"><div className="flex items-center justify-between border-b px-4 py-3"><h2 className="text-sm font-semibold">{t.cart}</h2><ShoppingBag className="size-4 text-muted-foreground"/></div><div className="min-h-48 space-y-2 p-3">{lines.length === 0 ? <p className="grid min-h-40 place-items-center text-center text-xs text-muted-foreground">{t.empty}</p> : lines.map((line) => <div key={line.id} className="flex items-center gap-2 rounded-lg bg-muted/50 p-2"><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium">{line.name}</p><p className="text-[11px] text-muted-foreground">{money(line.price, lang)}</p></div><div className="flex items-center gap-1"><Button size="icon-xs" variant="ghost" aria-label={`Remove ${line.name}`} onClick={() => adjust(line, -1)}><Minus /></Button><span className="w-4 text-center text-xs tabular-nums">{line.qty}</span><Button size="icon-xs" variant="ghost" aria-label={`Add ${line.name}`} disabled={line.qty >= line.stock} onClick={() => adjust(line, 1)}><Plus /></Button></div></div>)}</div><div className="border-t p-4"><div className="mb-3 flex items-center justify-between text-sm font-semibold"><span>{t.total}</span><span>{money(total, lang)}</span></div><AnimatePresence mode="wait">{phase === "idle" && <motion.div key="idle" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><Button className="w-full" disabled={!lines.length} onClick={start}>{t.confirm}</Button></motion.div>}{phase === "countdown" && <motion.div key="countdown" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><Button className="w-full" disabled><Clock3 className="animate-pulse" />{t.confirmIn} {seconds}s</Button></motion.div>}{phase === "paid" && <motion.div key="paid" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-2"><p className="text-center text-sm font-medium">{t.paid}</p><div className="grid grid-cols-2 gap-2"><Button onClick={complete}>{t.yes}</Button><Button variant="outline" onClick={() => setPhase("idle")}>{t.no}</Button></div></motion.div>}{phase === "done" && <motion.div key="done" initial={{ scale: .96, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} className="text-center text-sm font-medium text-emerald-600 dark:text-emerald-400"><Check className="mx-auto mb-1 size-5"/>Complete</motion.div>}</AnimatePresence></div></aside>
    </div>
  </div>
}
