import { getServerSession } from "next-auth"
import { asc, eq } from "drizzle-orm"
import { NextRequest, NextResponse } from "next/server"
import { authOptions } from "@/lib/auth"
import { db } from "@/lib/db"
import { posCategories } from "@/lib/db/schema"
import { assertPosPermission } from "@/lib/pos/server"
export const runtime = "nodejs"
export async function GET(_: NextRequest, { params }: { params: Promise<{ storeId: string }> }) { const s = await getServerSession(authOptions); if (!s?.user.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { storeId } = await params; try { await assertPosPermission(s.user.id, storeId, "catalog:read") } catch { return NextResponse.json({ error: "Forbidden" }, { status: 403 }) }; return NextResponse.json(await db.select().from(posCategories).where(eq(posCategories.storeId, storeId)).orderBy(asc(posCategories.sortOrder), asc(posCategories.name))) }
export async function POST(req: NextRequest, { params }: { params: Promise<{ storeId: string }> }) { const s = await getServerSession(authOptions); if (!s?.user.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { storeId } = await params; try { await assertPosPermission(s.user.id, storeId, "catalog:write") } catch { return NextResponse.json({ error: "Forbidden" }, { status: 403 }) }; const body = await req.json().catch(() => null) as { name?: unknown; description?: unknown; sortOrder?: unknown } | null; if (!body || typeof body.name !== "string" || !body.name.trim() || body.name.trim().length > 48 || (body.sortOrder !== undefined && !Number.isInteger(body.sortOrder))) return NextResponse.json({ error: "Invalid category" }, { status: 400 }); const [category] = await db.insert(posCategories).values({ storeId, name: body.name.trim(), description: typeof body.description === "string" ? body.description.slice(0, 140) : null, sortOrder: Number(body.sortOrder ?? 0) }).returning(); return NextResponse.json(category, { status: 201 }) }
