import { and, eq, inArray, isNull } from "drizzle-orm"
import { NextRequest, NextResponse } from "next/server"
import { db } from "@/lib/db"
import { posItems, posOrderItems, posOrders, posStores } from "@/lib/db/schema"
import { code } from "@/lib/pos/server"
export const runtime = "nodejs"
type Line = { itemId?: unknown; quantity?: unknown; note?: unknown }
export async function POST(req: NextRequest, { params }: { params: Promise<{ storeSlug: string }> }) {
  const { storeSlug } = await params; const body = await req.json().catch(() => null) as { customerName?: unknown; lines?: unknown; note?: unknown } | null
  if (!body || typeof body.customerName !== "string" || !body.customerName.trim() || body.customerName.trim().length > 80 || !Array.isArray(body.lines) || !body.lines.length || body.lines.length > 50) return NextResponse.json({ error: "Invalid order" }, { status: 400 })
  const lines = body.lines as Line[]; const quantities = new Map<string, number>()
  for (const line of lines) { if (typeof line.itemId !== "string" || !Number.isInteger(line.quantity) || Number(line.quantity) < 1 || Number(line.quantity) > 99) return NextResponse.json({ error: "Invalid line" }, { status: 400 }); quantities.set(line.itemId, (quantities.get(line.itemId) ?? 0) + Number(line.quantity)) }
  try { const order = await db.transaction(async (tx) => { const [store] = await tx.select().from(posStores).where(storeSlug.length === 36 ? eq(posStores.id, storeSlug) : eq(posStores.slug, storeSlug)).limit(1); if (!store || !store.isOpen) throw new Error("STORE_CLOSED"); const ids = [...quantities.keys()].sort(); const catalog = await tx.select().from(posItems).where(and(eq(posItems.storeId, store.id), inArray(posItems.id, ids), eq(posItems.available, true), isNull(posItems.deletedAt))).orderBy(posItems.id).for("update"); if (catalog.length !== ids.length) throw new Error("UNAVAILABLE"); let subtotal = 0; const rows = catalog.map((item) => { const quantity = quantities.get(item.id)!; if (item.trackStock && item.stockOnHand < quantity) throw new Error("OUT_OF_STOCK"); const lineTotal = Number(item.price) * quantity; subtotal += lineTotal; return { itemId: item.id, nameSnapshot: item.name, unitPrice: item.price, quantity, lineTotal: String(lineTotal.toFixed(2)), note: typeof lines.find((line) => line.itemId === item.id)?.note === "string" ? String(lines.find((line) => line.itemId === item.id)?.note).slice(0, 240) : null } }); const accessCode = code(8); const [created] = await tx.insert(posOrders).values({ storeId: store.id, orderNumber: `POS-${code(6)}`, accessCode, customerName: String(body.customerName ?? "").trim(), currency: store.currency, subtotal: String(subtotal.toFixed(2)), total: String(subtotal.toFixed(2)), note: typeof body.note === "string" ? body.note.slice(0, 500) : null, status: "submitted" }).returning(); await tx.insert(posOrderItems).values(rows.map((line) => ({ ...line, orderId: created.id }))); return created }); return NextResponse.json({ id: order.id, orderNumber: order.orderNumber, accessCode: order.accessCode, total: order.total, currency: order.currency }, { status: 201 }) } catch (error) { const message = error instanceof Error ? error.message : "ORDER_FAILED"; const status = ["STORE_CLOSED", "UNAVAILABLE", "OUT_OF_STOCK"].includes(message) ? 409 : 500; return NextResponse.json({ error: message }, { status }) }
}
