import { getServerSession } from "next-auth"
import { and, asc, eq, inArray, sql } from "drizzle-orm"
import { NextResponse } from "next/server"
import { authOptions } from "@/lib/auth"
import { db } from "@/lib/db"
import { posItems, posOrderItems, posOrders, posStockMovements } from "@/lib/db/schema"
import { assertPosPermission } from "@/lib/pos/server"
export const runtime = "nodejs"
export async function POST(_: Request, { params }: { params: Promise<{ storeId: string; orderId: string }> }) { const s = await getServerSession(authOptions); if (!s?.user.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { storeId, orderId } = await params; try { await assertPosPermission(s.user.id, storeId, "payment:collect") } catch { return NextResponse.json({ error: "Forbidden" }, { status: 403 }) }
  try { const order = await db.transaction(async (tx) => { const [order] = await tx.select().from(posOrders).where(and(eq(posOrders.id, orderId), eq(posOrders.storeId, storeId))).for("update").limit(1); if (!order) throw new Error("NOT_FOUND"); if (order.paymentStatus === "paid") return order; if (order.status === "cancelled" || order.status === "expired") throw new Error("NOT_PAYABLE"); const lines = await tx.select().from(posOrderItems).where(eq(posOrderItems.orderId, orderId)); const itemIds = lines.flatMap((line) => line.itemId ? [line.itemId] : []).sort(); const items = itemIds.length ? await tx.select().from(posItems).where(inArray(posItems.id, itemIds)).orderBy(asc(posItems.id)).for("update") : []; for (const line of lines) { const item = items.find((candidate) => candidate.id === line.itemId); if (!item || !item.available) throw new Error("ITEM_UNAVAILABLE"); if (item.trackStock && item.stockOnHand < line.quantity) throw new Error("OUT_OF_STOCK") }
    for (const line of lines) { const item = items.find((candidate) => candidate.id === line.itemId)!; if (item.trackStock) { const [updated] = await tx.update(posItems).set({ stockOnHand: sql`${posItems.stockOnHand} - ${line.quantity}`, version: sql`${posItems.version} + 1`, updatedAt: new Date() }).where(and(eq(posItems.id, item.id), sql`${posItems.stockOnHand} >= ${line.quantity}`)).returning({ stock: posItems.stockOnHand }); if (!updated) throw new Error("OUT_OF_STOCK"); await tx.insert(posStockMovements).values({ storeId, itemId: item.id, orderId, type: "sale", quantityDelta: -line.quantity, balanceAfter: updated.stock, actorId: s.user.id }) } }
    const [completed] = await tx.update(posOrders).set({ status: "completed", paymentStatus: "paid", cashierId: s.user.id, paidAt: new Date(), updatedAt: new Date(), version: sql`${posOrders.version} + 1` }).where(eq(posOrders.id, orderId)).returning(); return completed }); return NextResponse.json(order) } catch (error) { const message = error instanceof Error ? error.message : "CHECKOUT_FAILED"; return NextResponse.json({ error: message }, { status: message === "NOT_FOUND" ? 404 : 409 }) }
}
