import { getServerSession } from "next-auth"
import { and, eq } from "drizzle-orm"
import { NextRequest, NextResponse } from "next/server"
import { authOptions } from "@/lib/auth"
import { db } from "@/lib/db"
import { posInvites, posRoles } from "@/lib/db/schema"
import { hashInviteToken } from "@/lib/pos/invite-token"
import { assertPosPermission } from "@/lib/pos/server"
export const runtime = "nodejs"
export async function GET(_: NextRequest, { params }: { params: Promise<{ storeId: string }> }) { const s = await getServerSession(authOptions); if (!s?.user.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { storeId } = await params; try { await assertPosPermission(s.user.id, storeId, "member:manage") } catch { return NextResponse.json({ error: "Forbidden" }, { status: 403 }) }; return NextResponse.json(await db.select({ id: posInvites.id, email: posInvites.email, status: posInvites.status, expiresAt: posInvites.expiresAt, roleName: posRoles.name }).from(posInvites).innerJoin(posRoles, eq(posInvites.roleId, posRoles.id)).where(eq(posInvites.storeId, storeId))) }
export async function POST(req: NextRequest, { params }: { params: Promise<{ storeId: string }> }) { const s = await getServerSession(authOptions); if (!s?.user.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { storeId } = await params; try { await assertPosPermission(s.user.id, storeId, "member:manage") } catch { return NextResponse.json({ error: "Forbidden" }, { status: 403 }) }; const body = await req.json().catch(() => null) as { email?: unknown; roleId?: unknown } | null; if (!body || typeof body.email !== "string" || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(body.email) || typeof body.roleId !== "string") return NextResponse.json({ error: "Invalid invite" }, { status: 400 }); const [role] = await db.select({ id: posRoles.id }).from(posRoles).where(and(eq(posRoles.id, body.roleId), eq(posRoles.storeId, storeId))).limit(1); if (!role) return NextResponse.json({ error: "Role not found" }, { status: 404 }); const token = crypto.randomUUID().replace(/-/g, ""); const [invite] = await db.insert(posInvites).values({ storeId, roleId: role.id, email: body.email.toLowerCase(), tokenHash: await hashInviteToken(token), invitedBy: s.user.id, expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000) }).returning({ id: posInvites.id, email: posInvites.email, expiresAt: posInvites.expiresAt }); return NextResponse.json({ ...invite, token, inviteUrl: `/pos/invite/${token}` }, { status: 201 }) }
