import { getServerSession } from "next-auth"
import { and, asc, eq, inArray } from "drizzle-orm"
import { NextRequest, NextResponse } from "next/server"
import { authOptions } from "@/lib/auth"
import { db } from "@/lib/db"
import { posOrderItems, posOrders } from "@/lib/db/schema"
import { assertPosPermission } from "@/lib/pos/server"
export const runtime = "nodejs"
const allowed = ["accepted", "preparing", "ready"] as const
export async function GET(_: NextRequest, { params }: { params: Promise<{ storeId: string }> }) { const s = await getServerSession(authOptions); if (!s?.user.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { storeId } = await params; try { await assertPosPermission(s.user.id, storeId, "kitchen:read") } catch { return NextResponse.json({ error: "Forbidden" }, { status: 403 }) }; const orders = await db.select().from(posOrders).where(and(eq(posOrders.storeId, storeId), inArray(posOrders.status, ["submitted", ...allowed]))).orderBy(asc(posOrders.createdAt)).limit(100); const lines = orders.length ? await db.select().from(posOrderItems).where(inArray(posOrderItems.orderId, orders.map((order) => order.id))) : []; return NextResponse.json(orders.map((order) => ({ ...order, lines: lines.filter((line) => line.orderId === order.id) })), { headers: { "Cache-Control": "no-store" } }) }
export async function PATCH(req: NextRequest, { params }: { params: Promise<{ storeId: string }> }) { const s = await getServerSession(authOptions); if (!s?.user.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { storeId } = await params; try { await assertPosPermission(s.user.id, storeId, "kitchen:update") } catch { return NextResponse.json({ error: "Forbidden" }, { status: 403 }) }; const body = await req.json().catch(() => null) as { orderId?: unknown; status?: unknown } | null; if (!body || typeof body.orderId !== "string" || !allowed.includes(body.status as typeof allowed[number])) return NextResponse.json({ error: "Invalid kitchen update" }, { status: 400 }); const [updated] = await db.update(posOrders).set({ status: body.status as typeof allowed[number], updatedAt: new Date() }).where(and(eq(posOrders.id, body.orderId), eq(posOrders.storeId, storeId))).returning(); return updated ? NextResponse.json(updated) : NextResponse.json({ error: "Not found" }, { status: 404 }) }
