import { getServerSession } from "next-auth"
import { and, eq } from "drizzle-orm"
import { NextRequest, NextResponse } from "next/server"
import { authOptions } from "@/lib/auth"
import { db } from "@/lib/db"
import { posItems } from "@/lib/db/schema"
import { assertPosPermission } from "@/lib/pos/server"
export const runtime = "nodejs"
type Body = { name?: unknown; description?: unknown; price?: unknown; available?: unknown; trackStock?: unknown; stockOnHand?: unknown; lowStockAt?: unknown; categoryId?: unknown; prepStation?: unknown }
export async function PATCH(req: NextRequest, { params }: { params: Promise<{ storeId: string; itemId: string }> }) { const s = await getServerSession(authOptions); if (!s?.user.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { storeId, itemId } = await params; try { await assertPosPermission(s.user.id, storeId, "catalog:write") } catch { return NextResponse.json({ error: "Forbidden" }, { status: 403 }) }; const body = await req.json().catch(() => null) as Body | null; if (!body || (body.name !== undefined && (typeof body.name !== "string" || !body.name.trim() || body.name.trim().length > 80)) || (body.price !== undefined && (!Number.isFinite(Number(body.price)) || Number(body.price) < 0)) || (body.stockOnHand !== undefined && (!Number.isInteger(body.stockOnHand) || Number(body.stockOnHand) < 0))) return NextResponse.json({ error: "Invalid item" }, { status: 400 }); const [item] = await db.update(posItems).set({ ...(typeof body.name === "string" ? { name: body.name.trim() } : {}), ...(typeof body.description === "string" ? { description: body.description.slice(0, 500) } : {}), ...(body.price !== undefined ? { price: String(body.price) } : {}), ...(typeof body.available === "boolean" ? { available: body.available } : {}), ...(typeof body.trackStock === "boolean" ? { trackStock: body.trackStock } : {}), ...(body.stockOnHand !== undefined ? { stockOnHand: Number(body.stockOnHand) } : {}), ...(body.lowStockAt !== undefined && Number.isInteger(body.lowStockAt) ? { lowStockAt: Number(body.lowStockAt) } : {}), ...(typeof body.categoryId === "string" || body.categoryId === null ? { categoryId: body.categoryId } : {}), ...(typeof body.prepStation === "string" ? { prepStation: body.prepStation.slice(0, 48) } : {}), updatedAt: new Date() }).where(and(eq(posItems.id, itemId), eq(posItems.storeId, storeId))).returning(); return item ? NextResponse.json(item) : NextResponse.json({ error: "Not found" }, { status: 404 }) }
export async function DELETE(_: NextRequest, { params }: { params: Promise<{ storeId: string; itemId: string }> }) { const s = await getServerSession(authOptions); if (!s?.user.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { storeId, itemId } = await params; try { await assertPosPermission(s.user.id, storeId, "catalog:write") } catch { return NextResponse.json({ error: "Forbidden" }, { status: 403 }) }; const [item] = await db.update(posItems).set({ available: false, deletedAt: new Date(), updatedAt: new Date() }).where(and(eq(posItems.id, itemId), eq(posItems.storeId, storeId))).returning({ id: posItems.id }); return item ? NextResponse.json({ ok: true }) : NextResponse.json({ error: "Not found" }, { status: 404 }) }
