import { getServerSession } from "next-auth"
import { eq } from "drizzle-orm"
import { NextRequest, NextResponse } from "next/server"
import { authOptions } from "@/lib/auth"
import { db } from "@/lib/db"
import { posStores } from "@/lib/db/schema"
import { assertPosPermission } from "@/lib/pos/server"
export const runtime = "nodejs"
export async function PATCH(req: NextRequest, { params }: { params: Promise<{ storeId: string }> }) { const s = await getServerSession(authOptions); if (!s?.user.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { storeId } = await params; try { await assertPosPermission(s.user.id, storeId, "store:manage") } catch { return NextResponse.json({ error: "Forbidden" }, { status: 403 }) }; const body = await req.json().catch(() => null) as Record<string, unknown> | null; if (!body || (body.name !== undefined && (typeof body.name !== "string" || !body.name.trim() || body.name.trim().length > 20)) || (body.description !== undefined && (typeof body.description !== "string" || body.description.length > 100)) || (body.telephone !== undefined && (typeof body.telephone !== "string" || body.telephone.length > 24))) return NextResponse.json({ error: "Invalid store details" }, { status: 400 }); const [store] = await db.update(posStores).set({ ...(typeof body.name === "string" ? { name: body.name.trim() } : {}), ...(typeof body.description === "string" ? { description: body.description } : {}), ...(typeof body.telephone === "string" ? { telephone: body.telephone } : {}), ...(typeof body.address === "string" ? { address: body.address.slice(0, 240) } : {}), ...(typeof body.imageUrl === "string" || body.imageUrl === null ? { imageUrl: body.imageUrl } : {}), ...(typeof body.isOpen === "boolean" ? { isOpen: body.isOpen } : {}), ...(body.currency === "IDR" || body.currency === "USD" ? { currency: body.currency } : {}), updatedAt: new Date() }).where(eq(posStores.id, storeId)).returning(); return store ? NextResponse.json(store) : NextResponse.json({ error: "Not found" }, { status: 404 }) }
